### ISSUE TITLE
Where are the datasets? lol

### ISSUE THREAD

**Issue by danvillaba** [Santiago-Restrepo/my-first-etl-project#1]

**Comment by Santiago-Restrepo** [comment]
My completely bad hahaha, I have added this steps to get the datasets in a manual way, hope improve this flow later:

---

## Setting Up Datasets

Before running this project, you'll need to create a `datasets` folder and place the necessary CSV files from the Kaggle dataset inside it. Follow these steps:

1. Create a `datasets` folder in the root directory of the project:

   ```bash
   mkdir datasets
   ```

2. Download the following CSV files from the [Kaggle dataset](https://www.kaggle.com/datasets/joebeachcapital/hotel-reviews?select=reviews.csv):

   - `reviews.csv`
   - `offerings.csv`

3. Place the downloaded CSV files into the `datasets` folder.

**Comment by danvillaba** [comment]
that works 🚀
